### ISSUE TITLE
Specified resource name invalid: length 64 > 48

### ISSUE THREAD

**Issue by ohkeenan** [LINBIT/linstor-docker-volume-go#1]
Hi there,

Installed Linstor on Proxmox. Works great with kvm / lvm.

Followed the instructions and have a [working](https://www.linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-docker-linstor-install) Linstor cluster. 

Created docker volume and it exists:

	 root@hyp3:~# linstor v l
	╭────────────────────────────────────────────────────────────────────────────────────────────────────────╮
	┊ Node ┊ Resource      ┊ StoragePool  ┊ VolNr ┊ MinorNr ┊ DeviceName    ┊  Allocated ┊ InUse  ┊    State ┊
	╞════════════════════════════════════════════════════════════════════════════════════════════════════════╡
	┊ hyp3 ┊ elastic_db    ┊ pool_lildata ┊     0 ┊    1003 ┊ /dev/drbd1003 ┊ 500.11 GiB ┊ Unused ┊ UpToDate ┊
	┊ hyp4 ┊ elastic_db    ┊ pool_lildata ┊     0 ┊    1003 ┊ /dev/drbd1003 ┊ 500.11 GiB ┊ Unused ┊ UpToDate ┊
	┊ hyp3 ┊ optimus_data  ┊ pool_optimus ┊     0 ┊    1001 ┊ /dev/drbd1001 ┊   1.47 TiB ┊ Unused ┊ UpToDate ┊
	┊ hyp4 ┊ optimus_data  ┊ pool_optimus ┊     0 ┊    1001 ┊ /dev/drbd1001 ┊   1.47 TiB ┊ Unused ┊ UpToDate ┊
	┊ hyp3 ┊ vm-100-disk-1 ┊ pool_optimus ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊ 300.07 GiB ┊ Unused ┊ UpToDate ┊
	┊ hyp4 ┊ vm-100-disk-1 ┊ pool_optimus ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊ 300.07 GiB ┊ InUse  ┊ UpToDate ┊
	┊ hyp3 ┊ vm-101-disk-1 ┊ pool_bigdata ┊     0 ┊    1002 ┊ /dev/drbd1002 ┊  32.01 GiB ┊ Unused ┊ UpToDate ┊
	┊ hyp4 ┊ vm-101-disk-1 ┊ pool_bigdata ┊     0 ┊    1002 ┊ /dev/drbd1002 ┊  32.01 GiB ┊ Unused ┊ UpToDate ┊
	┊ hyp3 ┊ vm-102-disk-1 ┊ pool_lildata ┊     0 ┊    1004 ┊ /dev/drbd1004 ┊  32.01 GiB ┊ Unused ┊ UpToDate ┊
	┊ hyp4 ┊ vm-102-disk-1 ┊ pool_lildata ┊     0 ┊    1004 ┊ /dev/drbd1004 ┊  32.01 GiB ┊ Unused ┊ UpToDate ┊
	╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Docker shows it:

	user@worker1:~$ docker volume ls
	DRIVER                                VOLUME NAME
	convoy                                elastic
	linbit/linstor-docker-volume:latest   elastic_db

But trying to create a container to use it produces an error:

    ohkeenan@worker1:~$ docker run -it --rm --name=xfer -v elastic_db --volume-driver linbit/linstor-docker-volume alpine:latest
    docker: Error response from daemon: create 46bafa19a324786670eb7312cd3c3e7cbe6f9404305945c30234911a975834fa: VolumeDriver.Create: Message: 'The specified resource name '46bafa19a324786670eb7312cd3c3e7cbe6f9404305945c30234911a975834fa' is invalid.'; Cause: 'Invalid name: Name length 64 is greater than maximum length 48'; Details: 'Resource definition: 46bafa19a324786670eb7312cd3c3e7cbe6f9404305945c30234911a975834fa'; Reports: '[5ECBD47C-00000-000017]'.
	See 'docker run --help'.

Full error:

	ERROR REPORT 5ECBD47C-00000-000017

	============================================================

	Application:                        LINBIT® LINSTOR
	Module:                             Controller
	Version:                            1.7.1
	Build ID:                           6760637d6fae7a5862103ced4ea0ab0a758861f9
	Build time:                         2020-05-14T12:55:08+00:00
	Error time:                         2020-05-26 20:57:10
	Node:                               hyp3
	Peer:                               RestClient(192.168.5.190; 'Go-http-client/1.1')

	============================================================

	Reported error:
	===============

	Category:                           Exception
	Class name:                         InvalidNameException
	Class canonical name:               com.linbit.InvalidNameException
	Generated at:                       Method 'nameCheck', Source file 'Checks.java', Line #79

	Error message:                      Invalid name: Name length 64 is greater than maximum length 48

	Error context:
		The specified resource name '46bafa19a324786670eb7312cd3c3e7cbe6f9404305945c30234911a975834fa' is invalid.

	Call backtrace:

		Method                                   Native Class:Line number
		nameCheck                                N      com.linbit.Checks:79
		<init>                                   N      com.linbit.linstor.core.identifier.ResourceName:34
		asRscName                                N      com.linbit.linstor.LinstorParsingUtils:192
		createRscDfn                             N      com.linbit.linstor.core.apicallhandler.controller.CtrlRscDfnApiCallHandler:544
		createResourceDefinition                 N      com.linbit.linstor.core.apicallhandler.controller.CtrlRscDfnApiCallHandler:193
		createResourceDefinition                 N      com.linbit.linstor.core.apicallhandler.controller.CtrlApiCallHandler:211
		lambda$createResourceDefinition$3        N      com.linbit.linstor.api.rest.v1.ResourceDefinitions:141
		doInScope                                N      com.linbit.linstor.api.rest.v1.RequestHelper:231
		createResourceDefinition                 N      com.linbit.linstor.api.rest.v1.ResourceDefinitions:124
		invoke                                   N      jdk.internal.reflect.GeneratedMethodAccessor10:unknown
		invoke                                   N      jdk.internal.reflect.DelegatingMethodAccessorImpl:43
		invoke                                   N      java.lang.reflect.Method:566
		lambda$static$0                          N      org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory:52
		run                                      N      org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1:124
		invoke                                   N      org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher:167
		doDispatch                               N      org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker:176
		dispatch                                 N      org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher:79
		invoke                                   N      org.glassfish.jersey.server.model.ResourceMethodInvoker:469
		apply                                    N      org.glassfish.jersey.server.model.ResourceMethodInvoker:391
		apply                                    N      org.glassfish.jersey.server.model.ResourceMethodInvoker:80
		run                                      N      org.glassfish.jersey.server.ServerRuntime$1:253
		call                                     N      org.glassfish.jersey.internal.Errors$1:248
		call                                     N      org.glassfish.jersey.internal.Errors$1:244
		process                                  N      org.glassfish.jersey.internal.Errors:292
		process                                  N      org.glassfish.jersey.internal.Errors:274
		process                                  N      org.glassfish.jersey.internal.Errors:244
		runInScope                               N      org.glassfish.jersey.process.internal.RequestScope:265
		process                                  N      org.glassfish.jersey.server.ServerRuntime:232
		handle                                   N      org.glassfish.jersey.server.ApplicationHandler:680
		service                                  N      org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer:356
		run                                      N      org.glassfish.grizzly.http.server.HttpHandler$1:200
		doWork                                   N      org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker:569
		run                                      N      org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker:549
		run                                      N      java.lang.Thread:834

**Comment by rck** [comment]
reading the man page helps:
```
-v|--volume[=[[HOST-DIR:]CONTAINER-DIR[:OPTIONS]]]
          Create a bind mount. If you specify, -v /HOST-DIR:/CONTAINER-DIR, Docker
          bind mounts /HOST-DIR in the host to /CONTAINER-DIR in the Docker
          container. If 'HOST-DIR' is omitted,  Docker automatically creates the new
          volume on the host.
```
You only specified the `CONTAINER-DIR` part, so `docker` tried to create a new volume with a random name. This random name is too long. So please just use it with both parts as documented in the users guide (e.g., `-v yourvol:/data`).

**Comment by ohkeenan** [comment]
Sorry :/

Thanks for the help
